updated

diff --git a/0x08-networking_basics_2/0-change_your_home_IP b/0x08-networking_basics_2/0-change_your_home_IP
--- a/0x08-networking_basics_2/0-change_your_home_IP
+++ b/0x08-networking_basics_2/0-change_your_home_IP
@@ -1,7 +1,21 @@
 #!/usr/bin/env bash
+# Configure resolution of localhost to 127.0.0.2 and facebook.com to 8.8.8.8
 
-# Configure localhost resolution
-echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
+if (( ${UID:-$(id -u)} ))
+then
+  echo 'Must be run as root'
+  exit 1
+fi
 
-# Configure facebook.com resolution
-echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
+if ! tempfile="$(mktemp)"
+then
+  echo 'Unable to create temporary file'
+  exit 1
+fi
+
+{ printf '%s\t%s\n' 127.0.0.2 localhost
+  printf '%s\t%s\n' 8.8.8.8   facebook.com
+  cat /etc/hosts
+} > "${tempfile}"
+
+cat -- "${tempfile}" > /etc/hosts
